language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
before_install:
  - composer install
script:
  - php vendor/bin/phpunit ./tests/
  - php vendor/bin/phpmd ./src/ text codesize,design,unusedcode

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm